server:
    port: 8888

spring:
  # mariadb settings
  datasource:
    # 접근하고 싶은 벤더사
    driver-class-name: org.mariadb.jdbc.Driver 
    # db접근하는 경로
    url: jdbc:mariadb://localhost:3306/inspire   # 마지막은 DB 이름
    # 유저정보
    username: root
    password: 1004qhfma!

  jpa:
    hibernate: # 테이블 스키마 생성
      # create, create-drop, update, none                                                                  
      ddl-auto: create
    # 콘솔출력
    show-sql: true
    properties:
      hibernate:
      # h2
      # dialect: org.hibernate.dialect.H2Dialect
      # mariadb
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # redis
  # docker exec -it redis-container redis-cli
  data : 
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 6000ms

#   ai:
#     openai:
#       model: ${OPEN_AI_MODEL}
#       api:
#         key: ${OPEN_AI_KEY}
#         url: ${OPEN_AI_URL}

# # mybatis settings
# mybatis:
#   mapper-locations: /mappers/**/*Mapper.xml
#   config-location: classpath:/mappers/config/mybatis-config.xml

jwt:
  secret: lg_cns_am_inspire_04_project_secret_key_for_jwt

# openApi:
#   serviceKey: ${SERVICE_KEY}
#   callBackUrl: ${CALLBACKURL}
#   dataType: ${TYPE}
